// Mocks generated by Mockito 5.4.6 from annotations
// in tutodecode/test/widget/app_shell_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:tutodecode/core/providers/search_provider.dart' as _i2;
import 'package:tutodecode/core/providers/settings_provider.dart' as _i11;
import 'package:tutodecode/core/providers/shell_provider.dart' as _i8;
import 'package:tutodecode/core/services/github_service.dart' as _i7;
import 'package:tutodecode/features/courses/data/course_repository.dart' as _i6;
import 'package:tutodecode/features/courses/providers/courses_provider.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SearchProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProvider extends _i1.Mock implements _i2.SearchProvider {
  MockSearchProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get ready => (super.noSuchMethod(
        Invocation.getter(#ready),
        returnValue: false,
      ) as bool);

  @override
  List<String> get favorites => (super.noSuchMethod(
        Invocation.getter(#favorites),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i2.SearchDocument? docById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #docById,
        [id],
      )) as _i2.SearchDocument?);

  @override
  _i3.Future<void> init(_i4.CoursesProvider? courses) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [courses],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> rebuildIndex(_i4.CoursesProvider? courses) =>
      (super.noSuchMethod(
        Invocation.method(
          #rebuildIndex,
          [courses],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i2.SearchResult> search(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {#limit: limit},
        ),
        returnValue: <_i2.SearchResult>[],
      ) as List<_i2.SearchResult>);

  @override
  _i3.Future<void> toggleFavorite(String? docId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [docId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CoursesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoursesProvider extends _i1.Mock implements _i4.CoursesProvider {
  MockCoursesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.Course> get courses => (super.noSuchMethod(
        Invocation.getter(#courses),
        returnValue: <_i6.Course>[],
      ) as List<_i6.Course>);

  @override
  List<String> get completed => (super.noSuchMethod(
        Invocation.getter(#completed),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get loaded => (super.noSuchMethod(
        Invocation.getter(#loaded),
        returnValue: false,
      ) as bool);

  @override
  bool get isUpdating => (super.noSuchMethod(
        Invocation.getter(#isUpdating),
        returnValue: false,
      ) as bool);

  @override
  bool get startupUpdateCheckDone => (super.noSuchMethod(
        Invocation.getter(#startupUpdateCheckDone),
        returnValue: false,
      ) as bool);

  @override
  int get totalChaptersCount => (super.noSuchMethod(
        Invocation.getter(#totalChaptersCount),
        returnValue: 0,
      ) as int);

  @override
  int get completedCount => (super.noSuchMethod(
        Invocation.getter(#completedCount),
        returnValue: 0,
      ) as int);

  @override
  double get overallProgress => (super.noSuchMethod(
        Invocation.getter(#overallProgress),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int courseChaptersCount(String? courseId) => (super.noSuchMethod(
        Invocation.method(
          #courseChaptersCount,
          [courseId],
        ),
        returnValue: 0,
      ) as int);

  @override
  int courseCompletedCount(String? courseId) => (super.noSuchMethod(
        Invocation.method(
          #courseCompletedCount,
          [courseId],
        ),
        returnValue: 0,
      ) as int);

  @override
  void selectChapter(
    String? courseId,
    String? chapterId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectChapter,
          [
            courseId,
            chapterId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleCompleted(
    String? courseId,
    String? chapterId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleCompleted,
          [
            courseId,
            chapterId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> checkForUpdatesAvailable({bool? markStartupDone = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForUpdatesAvailable,
          [],
          {#markStartupDone: markStartupDone},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i7.ModuleUpdateInfo>> listAvailableUpdates() =>
      (super.noSuchMethod(
        Invocation.method(
          #listAvailableUpdates,
          [],
        ),
        returnValue: _i3.Future<List<_i7.ModuleUpdateInfo>>.value(
            <_i7.ModuleUpdateInfo>[]),
      ) as _i3.Future<List<_i7.ModuleUpdateInfo>>);

  @override
  _i3.Future<_i7.ModuleDiff?> diffUpdate(String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #diffUpdate,
          [fileName],
        ),
        returnValue: _i3.Future<_i7.ModuleDiff?>.value(),
      ) as _i3.Future<_i7.ModuleDiff?>);

  @override
  _i3.Future<bool> rollbackModule(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #rollbackModule,
          [fileName],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> listRollbackCandidates() => (super.noSuchMethod(
        Invocation.method(
          #listRollbackCandidates,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<int> checkForUpdates() => (super.noSuchMethod(
        Invocation.method(
          #checkForUpdates,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> deleteModule(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #deleteModule,
          [fileName],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> syncSpecificModule(_i7.ModuleUpdateInfo? info) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncSpecificModule,
          [info],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShellProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockShellProvider extends _i1.Mock implements _i8.ShellProvider {
  MockShellProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  bool get showBackButton => (super.noSuchMethod(
        Invocation.getter(#showBackButton),
        returnValue: false,
      ) as bool);

  @override
  String get activeRoute => (super.noSuchMethod(
        Invocation.getter(#activeRoute),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#activeRoute),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateShell({
    String? title,
    List<_i10.Widget>? actions,
    bool? showBackButton,
    _i5.VoidCallback? onBack,
    String? activeRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateShell,
          [],
          {
            #title: title,
            #actions: actions,
            #showBackButton: showBackButton,
            #onBack: onBack,
            #activeRoute: activeRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setActiveRoute(String? route) => super.noSuchMethod(
        Invocation.method(
          #setActiveRoute,
          [route],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i11.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get offlineMode => (super.noSuchMethod(
        Invocation.getter(#offlineMode),
        returnValue: false,
      ) as bool);

  @override
  bool get zeroNetworkMode => (super.noSuchMethod(
        Invocation.getter(#zeroNetworkMode),
        returnValue: false,
      ) as bool);

  @override
  bool get securityUpdates => (super.noSuchMethod(
        Invocation.getter(#securityUpdates),
        returnValue: false,
      ) as bool);

  @override
  bool get contentUpdates => (super.noSuchMethod(
        Invocation.getter(#contentUpdates),
        returnValue: false,
      ) as bool);

  @override
  String get ollamaUrl => (super.noSuchMethod(
        Invocation.getter(#ollamaUrl),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#ollamaUrl),
        ),
      ) as String);

  @override
  String get ollamaModel => (super.noSuchMethod(
        Invocation.getter(#ollamaModel),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#ollamaModel),
        ),
      ) as String);

  @override
  String get tutorPersonality => (super.noSuchMethod(
        Invocation.getter(#tutorPersonality),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#tutorPersonality),
        ),
      ) as String);

  @override
  double get terminalFontSize => (super.noSuchMethod(
        Invocation.getter(#terminalFontSize),
        returnValue: 0.0,
      ) as double);

  @override
  String get terminalTheme => (super.noSuchMethod(
        Invocation.getter(#terminalTheme),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#terminalTheme),
        ),
      ) as String);

  @override
  String get appTheme => (super.noSuchMethod(
        Invocation.getter(#appTheme),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#appTheme),
        ),
      ) as String);

  @override
  _i10.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i10.ThemeMode.system,
      ) as _i10.ThemeMode);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setOfflineMode(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setOfflineMode,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setZeroNetworkMode(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setZeroNetworkMode,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setSecurityUpdates(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setSecurityUpdates,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setContentUpdates(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setContentUpdates,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setOllamaUrl(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setOllamaUrl,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setOllamaModel(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setOllamaModel,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setTutorPersonality(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setTutorPersonality,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setTerminalFontSize(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setTerminalFontSize,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setTerminalTheme(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setTerminalTheme,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setAppTheme(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setAppTheme,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearChatHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearChatHistory,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resetProgress() => (super.noSuchMethod(
        Invocation.method(
          #resetProgress,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
