// Mocks generated by Mockito 5.4.6 from annotations
// in tutodecode/test/unit/search_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tutodecode/core/services/github_service.dart' as _i5;
import 'package:tutodecode/features/courses/data/course_repository.dart' as _i3;
import 'package:tutodecode/features/courses/providers/courses_provider.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CoursesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoursesProvider extends _i1.Mock implements _i2.CoursesProvider {
  MockCoursesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Course> get courses => (super.noSuchMethod(
        Invocation.getter(#courses),
        returnValue: <_i3.Course>[],
      ) as List<_i3.Course>);

  @override
  List<String> get completed => (super.noSuchMethod(
        Invocation.getter(#completed),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get loaded => (super.noSuchMethod(
        Invocation.getter(#loaded),
        returnValue: false,
      ) as bool);

  @override
  bool get isUpdating => (super.noSuchMethod(
        Invocation.getter(#isUpdating),
        returnValue: false,
      ) as bool);

  @override
  bool get startupUpdateCheckDone => (super.noSuchMethod(
        Invocation.getter(#startupUpdateCheckDone),
        returnValue: false,
      ) as bool);

  @override
  int get totalChaptersCount => (super.noSuchMethod(
        Invocation.getter(#totalChaptersCount),
        returnValue: 0,
      ) as int);

  @override
  int get completedCount => (super.noSuchMethod(
        Invocation.getter(#completedCount),
        returnValue: 0,
      ) as int);

  @override
  double get overallProgress => (super.noSuchMethod(
        Invocation.getter(#overallProgress),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int courseChaptersCount(String? courseId) => (super.noSuchMethod(
        Invocation.method(
          #courseChaptersCount,
          [courseId],
        ),
        returnValue: 0,
      ) as int);

  @override
  int courseCompletedCount(String? courseId) => (super.noSuchMethod(
        Invocation.method(
          #courseCompletedCount,
          [courseId],
        ),
        returnValue: 0,
      ) as int);

  @override
  void selectChapter(
    String? courseId,
    String? chapterId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectChapter,
          [
            courseId,
            chapterId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleCompleted(
    String? courseId,
    String? chapterId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleCompleted,
          [
            courseId,
            chapterId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> checkForUpdatesAvailable({bool? markStartupDone = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForUpdatesAvailable,
          [],
          {#markStartupDone: markStartupDone},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.ModuleUpdateInfo>> listAvailableUpdates() =>
      (super.noSuchMethod(
        Invocation.method(
          #listAvailableUpdates,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ModuleUpdateInfo>>.value(
            <_i5.ModuleUpdateInfo>[]),
      ) as _i4.Future<List<_i5.ModuleUpdateInfo>>);

  @override
  _i4.Future<_i5.ModuleDiff?> diffUpdate(String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #diffUpdate,
          [fileName],
        ),
        returnValue: _i4.Future<_i5.ModuleDiff?>.value(),
      ) as _i4.Future<_i5.ModuleDiff?>);

  @override
  _i4.Future<bool> rollbackModule(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #rollbackModule,
          [fileName],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> listRollbackCandidates() => (super.noSuchMethod(
        Invocation.method(
          #listRollbackCandidates,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<int> checkForUpdates() => (super.noSuchMethod(
        Invocation.method(
          #checkForUpdates,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> deleteModule(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #deleteModule,
          [fileName],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> syncSpecificModule(_i5.ModuleUpdateInfo? info) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncSpecificModule,
          [info],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
